(()=>{const root=document.documentElement,toggleTheme=document.getElementById("themeToggle"),saved=localStorage.getItem("cliffcode-theme"),prefersDark=matchMedia("(prefers-color-scheme: dark)").matches;const setTheme=t=>{t==="dark"?root.setAttribute("data-theme","dark"):root.removeAttribute("data-theme");document.querySelector('meta[name="theme-color"]').content=t==="dark"?"#171717":"#ffffff";toggleTheme?.setAttribute("aria-pressed",String(t==="dark"))};setTheme(saved||(prefersDark?"dark":"light"));toggleTheme?.addEventListener("click",()=>{const n=root.getAttribute("data-theme")==="dark"?"light":"dark";localStorage.setItem("cliffcode-theme",n);setTheme(n)});

const inline=document.getElementById("inlineListen"),player=document.getElementById("stickyPlayer"),transport=document.getElementById("playerToggle"),timeEl=document.getElementById("playerTime"),speedBtn=document.getElementById("playerSpeed"),rew=document.getElementById("rewind15"),fwd=document.getElementById("forward15"),close=document.getElementById("closePlayer");
if(!inline||!player||!("speechSynthesis" in window)){if(inline)inline.hidden=true;return}
const narrateEls=[...document.querySelectorAll("[data-narrate]")];let fullText="",words=[],rate=1,playing=false,paused=false,baseOffset=0,currentWord=0,utterance=null,lastFollow=0,userScrollUntil=0;
function tokenize(){narrateEls.forEach(el=>{const raw=el.textContent.trim(),spacer=fullText?"\n\n":"";fullText+=spacer;const elementStart=fullText.length;fullText+=raw;const parts=raw.match(/\S+|\s+/g)||[];el.textContent="";let local=0;for(const part of parts){if(/^\s+$/.test(part)){el.appendChild(document.createTextNode(part));local+=part.length;continue}const span=document.createElement("span");span.className="narration-word";span.textContent=part;el.appendChild(span);words.push({start:elementStart+local,end:elementStart+local+part.length,span});local+=part.length}})}tokenize();
const fmt=s=>{s=Math.max(0,Math.floor(s));return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")};const wordForChar=c=>{let lo=0,hi=words.length-1,ans=0;while(lo<=hi){const m=(lo+hi)>>1;if(words[m].start<=c){ans=m;lo=m+1}else hi=m-1}return ans};const approxSeconds=i=>i/(2.55*rate);const setTransport=play=>{transport.innerHTML=play?'<span class="pause-bars" aria-hidden="true"><i></i><i></i></span>':'<span class="play-triangle" aria-hidden="true">▶</span>'};
function maybeFollow(){if(Date.now()<userScrollUntil||Date.now()-lastFollow<700)return;const el=words[currentWord]?.span;if(!el)return;const rect=el.getBoundingClientRect(),topGuard=105,bottomGuard=innerHeight*.76;if(rect.bottom>bottomGuard){lastFollow=Date.now();window.scrollBy({top:rect.bottom-bottomGuard+82,behavior:"smooth"})}else if(rect.top<topGuard){lastFollow=Date.now();window.scrollBy({top:rect.top-topGuard-20,behavior:"smooth"})}}
function paint(i){currentWord=Math.max(0,Math.min(words.length-1,i));for(let n=0;n<words.length;n++){words[n].span.classList.toggle("word-read",n<currentWord);words[n].span.classList.toggle("word-current",n===currentWord)}timeEl.textContent=fmt(approxSeconds(currentWord));maybeFollow()}
function speakFromWord(i){speechSynthesis.cancel();i=Math.max(0,Math.min(words.length-1,i));paint(i);baseOffset=words[i].start;utterance=new SpeechSynthesisUtterance(fullText.slice(baseOffset));utterance.lang="en";utterance.rate=rate;utterance.onboundary=e=>{if(e.name&&e.name!=="word")return;paint(wordForChar(baseOffset+(e.charIndex||0)))};utterance.onend=()=>{playing=false;paused=false;setTransport(false);timeEl.textContent=fmt(approxSeconds(words.length));paint(words.length-1)};utterance.onerror=()=>{playing=false;paused=false;setTransport(false)};playing=true;paused=false;setTransport(true);speechSynthesis.speak(utterance)}
function openPlayer(){player.hidden=false;document.body.classList.add("player-open")}function closePlayer(){speechSynthesis.cancel();playing=false;paused=false;player.hidden=true;document.body.classList.remove("player-open");setTransport(true);words.forEach(w=>w.span.classList.remove("word-read","word-current"));currentWord=0;timeEl.textContent="00:00"}
["touchstart","pointerdown","wheel"].forEach(evt=>window.addEventListener(evt,e=>{if(!player.contains(e.target))userScrollUntil=Date.now()+5000},{passive:true}));
inline.addEventListener("click",()=>{openPlayer();speakFromWord(currentWord||0)});transport.addEventListener("click",()=>{if(!playing){openPlayer();speakFromWord(currentWord||0);return}if(paused){speechSynthesis.resume();paused=false;setTransport(true)}else{speechSynthesis.pause();paused=true;setTransport(false)}});rew.addEventListener("click",()=>speakFromWord(Math.max(0,currentWord-Math.round(15*2.55*rate))));fwd.addEventListener("click",()=>speakFromWord(Math.min(words.length-1,currentWord+Math.round(15*2.55*rate))));speedBtn.addEventListener("click",()=>{const rates=[1,1.15,1.3,.9],idx=rates.indexOf(rate);rate=rates[(idx+1)%rates.length];speedBtn.textContent=(rate===1?"1":String(rate))+"×";if(playing&&!paused)speakFromWord(currentWord)});close.addEventListener("click",closePlayer);window.addEventListener("pagehide",()=>speechSynthesis.cancel())})();